services:
  mongodb:
    image: mongo:4.0-xenial
    ports: 
      - 27017:27017
    volumes:
      - ./db:/data/db
    
  app:
    build: ./webapp
    ports:
      - "3000:5000"
    environment:
      DB_HOST: mongodb://db/foobar
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/uploads
